# This is a basic workflow to help you get started with Actions

name: shell test

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name : run dir.sh
        shell: bash
        run: |
            korean=$(<directory\\korean.txt)
            upstream=$(<directory\\upstream.txt)
            echo "$korean"
            echo "$upstream"
            git checkout -b result

            echo "git clone repo"
            git clone "$korean"


            echo "copy python script"
            cp git_diff.py \Web-Dev-For-Beginners


            echo "cd working directory"
            cd ./Web-Dev-For-Beginners


            echo "add upstream"
            git remote add upstream "$upstream"

            echo "check repo"
            git remote -v

            echo "fetch upstream"
            git fetch "$upstream"


            # upstream branch
            echo "git checkout to upstream"
            git checkout -b upstream

            echo "run git_diff.py"
            python git_diff.py main upstream

            echo "in post"
            cp report_tree.md ../post


      
      - name : git config
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        run : |
              git config --global user.email "gaga2353@gmail.com"
              git config --global user.name "bmlsj"

      - name: Run auto.sh
        run: |
              chmod +rx auto.sh
              ./auto.sh
              echo "shell complete"
