name: shell test

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name : pwd
        run : pwd
        
      - name : run dir.sh
        shell: bash
        run: |
            chmod +rx dir.sh
            ./dir.sh
            echo "dir"
      
      - name : git config
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        run : |
              git config --global user.email "gaga2353@gmail.com"
              git config --global user.name "bmlsj"
      - name: Run auto.sh
        run: |
              chmod +rx auto.sh
              ./auto.sh
              echo "shell complete"
